"""
Django settings for humara_bharat project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from importlib.util import find_spec
from django.core.exceptions import ImproperlyConfigured
import os
import warnings



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_local_env(path):
    """Load a simple local .env without overriding real Render variables."""
    if not path.exists():
        return
    for raw_line in path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key:
            os.environ.setdefault(key, value)


_load_local_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-g4t47(p86n0+=95#t$147^*y1%e@92dlyd6^k3vqajjdj7r8o4',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get(
    'DEBUG',
    'False' if os.environ.get('RENDER') else 'True',
).lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        'ALLOWED_HOSTS',
        '127.0.0.1,localhost,.onrender.com',
    ).split(',')
    if host.strip()
]

render_hostname = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if render_hostname and render_hostname not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(render_hostname)

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        'CSRF_TRUSTED_ORIGINS',
        'https://*.onrender.com',
    ).split(',')
    if origin.strip()
]
if render_hostname:
    render_origin = f'https://{render_hostname}'
    if render_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(render_origin)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'indiaApp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'indiaApp.middleware.AnonymousReactionCookieMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
if find_spec('whitenoise'):
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'humara_bharat.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'humara_bharat.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASE_URL = os.environ.get('DATABASE_URL', '').strip()

# Render's filesystem is ephemeral. Falling back to SQLite in production would
# make verified petition signatures disappear on every deploy or instance
# restart, so production must use the attached PostgreSQL database.
if os.environ.get('RENDER') and not DATABASE_URL:
    raise ImproperlyConfigured(
        'DATABASE_URL is required on Render. Attach a persistent PostgreSQL '
        'database before starting Unmute India.'
    )

if DATABASE_URL:
    import dj_database_url

    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=not DEBUG,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = Path(os.environ.get('STATIC_ROOT', BASE_DIR / 'staticfiles'))
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# User uploads must not live on Render's ephemeral filesystem. Supplying these
# variables switches every FileField to durable S3-compatible storage (AWS S3,
# Cloudflare R2, Backblaze, etc.). Local development intentionally keeps using
# MEDIA_ROOT.
MEDIA_STORAGE_BUCKET = os.environ.get('AWS_STORAGE_BUCKET_NAME', '').strip()
MEDIA_IS_REMOTE = bool(MEDIA_STORAGE_BUCKET)
if MEDIA_IS_REMOTE:
    media_options = {
        'bucket_name': MEDIA_STORAGE_BUCKET,
        'access_key': os.environ.get('AWS_ACCESS_KEY_ID'),
        'secret_key': os.environ.get('AWS_SECRET_ACCESS_KEY'),
        'region_name': os.environ.get('AWS_S3_REGION_NAME') or None,
        'endpoint_url': os.environ.get('AWS_S3_ENDPOINT_URL') or None,
        'default_acl': None,
        'file_overwrite': False,
        'querystring_auth': True,
        'querystring_expire': 3600,
    }
    media_options = {key: value for key, value in media_options.items() if value is not None}

STORAGES = {
    'default': {
        'BACKEND': (
            'storages.backends.s3.S3Storage'
            if MEDIA_IS_REMOTE
            else 'django.core.files.storage.FileSystemStorage'
        ),
        **({'OPTIONS': media_options} if MEDIA_IS_REMOTE else {}),
    },
    'staticfiles': {
        'BACKEND': (
            'whitenoise.storage.CompressedManifestStaticFilesStorage'
            if not DEBUG and find_spec('whitenoise')
            else 'django.contrib.staticfiles.storage.StaticFilesStorage'
        ),
    },
}
if os.environ.get('RENDER') and not MEDIA_IS_REMOTE:
    warnings.warn(
        'Durable media storage is not configured. Render can erase uploaded '
        'audio/video files after a restart. Set the AWS_* media variables.',
        RuntimeWarning,
    )
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'home'
FILE_UPLOAD_PERMISSIONS = 0o640
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
# Google Identity Services popup must retain a safe opener channel so its
# credential callback can return to the petition page.
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '3600'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Transactional email is console-only by default in development. Production
# credentials are supplied through environment variables, never source code.
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').strip().lower() in ('1','true','yes')
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False').strip().lower() in ('1','true','yes')
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '20'))
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID', '').strip()
PRIVATE_IDENTITY_HMAC_KEY = os.environ.get('PRIVATE_IDENTITY_HMAC_KEY', SECRET_KEY).strip()
TURNSTILE_SITE_KEY = os.environ.get('TURNSTILE_SITE_KEY', '').strip()
TURNSTILE_SECRET_KEY = os.environ.get('TURNSTILE_SECRET_KEY', '').strip()
PETITION_VERIFICATION_EXPIRY_HOURS = int(os.environ.get('PETITION_VERIFICATION_EXPIRY_HOURS', '24'))
SITE_URL = os.environ.get(
    'SITE_URL',
    f'https://{render_hostname}' if render_hostname else 'http://127.0.0.1:8000',
).rstrip('/')
TURNSTILE_TEST_MODE = DEBUG and os.environ.get('TURNSTILE_USE_TEST_KEYS', 'False').strip().lower() in ('1', 'true', 'yes')
if TURNSTILE_TEST_MODE:
    # Official Cloudflare dummy keys: valid on localhost/127.0.0.1 only because
    # this branch is impossible when DEBUG=False.
    TURNSTILE_SITE_KEY = '1x00000000000000000000AA'
    TURNSTILE_SECRET_KEY = '1x0000000000000000000000000000000AA'

if EMAIL_HOST == 'smtp.gmail.com':
    # Google displays app passwords grouped with spaces. SMTP expects the raw
    # 16-character value, so accept either form from Render's environment UI.
    EMAIL_HOST_PASSWORD = ''.join(EMAIL_HOST_PASSWORD.split())

if os.environ.get('RENDER'):
    required_email_settings = {
        'EMAIL_HOST': EMAIL_HOST,
        'EMAIL_HOST_USER': EMAIL_HOST_USER,
        'EMAIL_HOST_PASSWORD': EMAIL_HOST_PASSWORD,
        'DEFAULT_FROM_EMAIL': DEFAULT_FROM_EMAIL,
    }
    missing_email_settings = [key for key, value in required_email_settings.items() if not value]
    if 'noreply@localhost' in DEFAULT_FROM_EMAIL:
        missing_email_settings.append('DEFAULT_FROM_EMAIL (must use the authenticated sender)')
    if EMAIL_BACKEND.endswith('console.EmailBackend'):
        missing_email_settings.append('EMAIL_BACKEND (must use SMTP in production)')
    if missing_email_settings:
        warnings.warn(
            'Production petition email is not configured: ' + ', '.join(missing_email_settings),
            RuntimeWarning,
        )
    if EMAIL_USE_TLS and EMAIL_USE_SSL:
        warnings.warn('Enable only one of EMAIL_USE_TLS or EMAIL_USE_SSL.', RuntimeWarning)

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Always send production request exceptions to Render's log stream. DEBUG stays
# disabled, so visitors never see internal paths, settings, or tracebacks.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'server': {
            'format': '{levelname} {asctime} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'server',
        },
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'indiaApp': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
