# Generated by Django 4.2.30 on 2026-07-22 07:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import indiaApp.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountabilityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('event_date', models.DateField()),
                ('summary', models.TextField()),
                ('source_url', models.URLField(blank=True)),
                ('verification_status', models.CharField(default='Awaiting verification', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListenerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=80)),
                ('role', models.CharField(choices=[('student', 'Student Listener'), ('senior', 'Senior Listener'), ('counsellor', 'Verified Counsellor'), ('legal', 'Legal Support Volunteer'), ('academic', 'Academic Support Volunteer'), ('coordinator', 'Support Coordinator'), ('moderator', 'Moderator'), ('admin', 'Super Admin')], default='student', max_length=20)),
                ('introduction', models.TextField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('max_active_conversations', models.PositiveSmallIntegerField(default=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=140)),
                ('body', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('approved', models.BooleanField(db_index=True, default=False)),
                ('comment_mode', models.CharField(choices=[('support', 'Support only'), ('advice', 'Advice welcome'), ('none', 'No comments')], default='support', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupportResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('verified', models.BooleanField(default=False)),
                ('reviewed_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('motivation', models.TextField()),
                ('status', models.CharField(default='new', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('anonymous_preferred', models.BooleanField(default=True)),
                ('email_updates', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoryReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(max_length=40)),
                ('reaction', models.CharField(choices=[('with_you', 'I am with you'), ('not_alone', 'You are not alone'), ('listening', 'I am listening'), ('valid', 'Your feelings are valid'), ('strength', 'Sending strength')], max_length=16)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='indiaApp.story')),
            ],
        ),
        migrations.CreateModel(
            name='ListeningRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('video', 'Video')], default='text', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('media', models.FileField(blank=True, upload_to=indiaApp.models.private_upload, validators=[django.core.validators.FileExtensionValidator(['mp3', 'm4a', 'wav', 'ogg', 'webm', 'mp4', 'mov'])])),
                ('anonymous', models.BooleanField(default=True)),
                ('wants_reply', models.BooleanField(default=True)),
                ('support_preference', models.CharField(blank=True, choices=[('listen', 'Just listen'), ('reply', 'Send a supportive reply'), ('think', 'Help me think through this'), ('trusted', 'Help me talk to someone I trust'), ('unsure', 'I am not sure')], max_length=12)),
                ('privacy', models.CharField(default='private', editable=False, max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('active', 'Active'), ('closed', 'Closed')], db_index=True, default='new', max_length=12)),
                ('safety_flag', models.BooleanField(db_index=True, default=False)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indiaApp.listenerprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('internal', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='indiaApp.listeningrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=160)),
                ('object_reference', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='storyreaction',
            constraint=models.UniqueConstraint(fields=('story', 'session_key', 'reaction'), name='unique_story_reaction'),
        ),
    ]
