# Generated by Django 4.2.30 on 2026-07-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField()),
                ('authority', models.CharField(max_length=180)),
                ('date_sent', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_sent', 'Not sent'), ('sent', 'Sent'), ('none', 'No response'), ('partial', 'Partial response'), ('full', 'Full response'), ('disputed', 'Disputed response')], default='not_sent', max_length=20)),
                ('response_date', models.DateField(blank=True, null=True)),
                ('response_text', models.TextField(blank=True)),
                ('response_source_url', models.URLField(blank=True)),
                ('follow_up_needed', models.BooleanField(default=False)),
                ('published', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EvidenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('document_date', models.DateField()),
                ('source_name', models.CharField(max_length=160)),
                ('source_url', models.URLField()),
                ('evidence_type', models.CharField(choices=[('notice', 'Official notice'), ('statement', 'Government statement'), ('court', 'Court document'), ('news', 'News report'), ('video', 'Protest video'), ('student', 'Student evidence')], max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('verified', models.BooleanField(db_index=True, default=False)),
                ('published', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PetitionSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('supporter_type', models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('teacher', 'Teacher'), ('citizen', 'Citizen')], max_length=12)),
                ('consent', models.BooleanField(default=False)),
                ('verified', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PromiseTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promise', models.CharField(max_length=220)),
                ('promise_date', models.DateField()),
                ('expected_action', models.TextField()),
                ('current_status', models.CharField(choices=[('announced', 'Announced'), ('pending', 'Pending'), ('partial', 'Partially completed'), ('complete', 'Completed'), ('contradicted', 'Contradicted'), ('none', 'No update')], default='announced', max_length=20)),
                ('source_url', models.URLField()),
                ('verified', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField(max_length=500)),
                ('name', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('anonymous', models.BooleanField(default=True)),
                ('consent', models.BooleanField(default=False)),
                ('approved', models.BooleanField(db_index=True, default=False)),
                ('upvotes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='accountabilityevent',
            name='category',
            field=models.CharField(choices=[('exam', 'Exam conducted'), ('allegation', 'Paper leak allegation'), ('response', 'Official response'), ('investigation', 'Investigation'), ('reexam', 'Re-exam'), ('protest', 'Student protest'), ('police', 'Police action'), ('statement', 'Minister statement'), ('court', 'Court update'), ('reform', 'Reform announcement'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='accountabilityevent',
            name='published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='accountabilityevent',
            name='related_document_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='accountabilityevent',
            name='related_video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='accountabilityevent',
            name='source_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='accountabilityevent',
            name='source_type',
            field=models.CharField(choices=[('official', 'Official record'), ('court', 'Court document'), ('video', 'Source video'), ('news', 'News report'), ('other', 'Other source')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='accountabilityevent',
            name='why_it_matters',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='petitionsignature',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_petition_email'),
        ),
    ]
