# Generated by Django 4.2.30 on 2026-07-22 09:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indiaApp', '0002_authorityresponse_evidencedocument_petitionsignature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='age_group',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='story',
            name='audio_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='content_warning',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='story',
            name='display_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='story',
            name='duration',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='story',
            name='face_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='public_media',
            field=models.FileField(blank=True, upload_to='stories/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'm4a', 'wav', 'ogg', 'webm', 'mp4', 'mov'])]),
        ),
        migrations.AddField(
            model_name='story',
            name='state',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='story',
            name='story_format',
            field=models.CharField(choices=[('text', 'Text'), ('voice', 'Voice'), ('video', 'Video')], db_index=True, default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='story',
            name='topic',
            field=models.CharField(choices=[('heard', 'Needed to be heard'), ('alone', 'I thought I was alone'), ('listened', 'Someone listened to me'), ('hope', 'I did not give up'), ('message', 'To another student'), ('exam', 'Exam pressure'), ('family', 'Family pressure'), ('college', 'College life'), ('coaching', 'Coaching pressure'), ('protest', 'Protest experience')], db_index=True, default='heard', max_length=20),
        ),
        migrations.AddField(
            model_name='story',
            name='transcript',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supportresource',
            name='audience',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='supportresource',
            name='availability',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='supportresource',
            name='official_source',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='StoryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('body', models.TextField(max_length=800)),
                ('approved', models.BooleanField(db_index=True, default=False)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='indiaApp.story')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
