# Generated by Django 4.2.30 on 2026-07-22 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indiaApp', '0003_story_age_group_story_audio_only_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(unique=True)),
                ('eyebrow_text', models.CharField(blank=True, max_length=100)),
                ('short_heading', models.CharField(max_length=220)),
                ('summary', models.TextField()),
                ('full_description', models.TextField(blank=True)),
                ('why_it_matters', models.TextField(blank=True)),
                ('primary_demand', models.TextField()),
                ('additional_demands', models.TextField(blank=True, help_text='One demand per line.')),
                ('questions', models.TextField(blank=True, help_text='One question per line.')),
                ('disclaimer', models.TextField(blank=True)),
                ('confirmation_email_content', models.TextField(blank=True)),
                ('verification_success_message', models.CharField(blank=True, max_length=240)),
                ('share_message', models.CharField(blank=True, max_length=280)),
                ('closing_statement', models.CharField(blank=True, max_length=240)),
                ('target_person', models.CharField(blank=True, max_length=160)),
                ('target_authority', models.CharField(blank=True, max_length=180)),
                ('petition_category', models.CharField(choices=[('resignation', 'Resignation'), ('accountability', 'Accountability'), ('investigation', 'Investigation'), ('exam_reform', 'Examination Reform'), ('student_protection', 'Student Protection'), ('public_apology', 'Public Apology'), ('compensation', 'Compensation'), ('institutional_action', 'Institutional Action'), ('other', 'Other')], default='other', max_length=30)),
                ('cover_image', models.ImageField(blank=True, upload_to='petitions/')),
                ('petition_status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('published', 'Published'), ('paused', 'Paused'), ('closed', 'Closed'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('signature_goal', models.PositiveIntegerField(default=1000)),
                ('allow_signatures', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('hide_supporter_names', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_to', models.CharField(blank=True, max_length=180)),
                ('authority_name', models.CharField(blank=True, max_length=180)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('submission_method', models.CharField(blank=True, max_length=100)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('submission_document', models.FileField(blank=True, upload_to='petition_documents/')),
                ('public_note', models.TextField(blank=True)),
                ('response_status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('submitted', 'Submitted'), ('acknowledged', 'Acknowledged'), ('no_response', 'No Response'), ('partial', 'Partial Response'), ('full', 'Full Response'), ('rejected', 'Rejected'), ('follow_up', 'Follow-Up Required')], default='not_submitted', max_length=30)),
                ('response_date', models.DateField(blank=True, null=True)),
                ('response_document', models.FileField(blank=True, upload_to='petition_responses/')),
                ('response_summary', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PetitionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('organisation', models.CharField(blank=True, max_length=160)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('required', 'Source Required'), ('review', 'Under Review'), ('verified', 'Verified'), ('disputed', 'Disputed'), ('outdated', 'Outdated')], default='required', max_length=12)),
                ('internal_reviewer_note', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PetitionUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('body', models.TextField()),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('raised', 'Raised'), ('submitted', 'Submitted'), ('awaiting', 'Awaiting Response'), ('partial', 'Partially Addressed'), ('addressed', 'Addressed'), ('rejected', 'Rejected'), ('none', 'No Public Response')], default='raised', max_length=12)),
                ('source_url', models.URLField(blank=True)),
                ('source_title', models.CharField(blank=True, max_length=180)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='petitionsignature',
            name='unique_petition_email',
        ),
        migrations.AddField(
            model_name='petitionsignature',
            name='ip_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='petitionsignature',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='petitionsignature',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate'), ('spam', 'Spam'), ('removed', 'Removed')], db_index=True, default='pending', max_length=12),
        ),
        migrations.AddField(
            model_name='petitionsignature',
            name='normalized_email',
            field=models.EmailField(db_index=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='petitionsignature',
            name='removal_reason',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='petitionsignature',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petitionsignature',
            name='token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petitionsignature',
            name='user_agent_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='petitionsignature',
            name='verification_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='petitionsignature',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='petitionsignature',
            name='supporter_type',
            field=models.CharField(choices=[('', 'Select your role'), ('student', 'Student'), ('parent', 'Parent'), ('teacher', 'Teacher'), ('educator', 'Educator'), ('volunteer', 'Volunteer'), ('citizen', 'Citizen'), ('other', 'Other')], max_length=12),
        ),
        migrations.AddField(
            model_name='studentdemand',
            name='related_petition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indiaApp.petition'),
        ),
        migrations.AddField(
            model_name='petitionupdate',
            name='petition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='indiaApp.petition'),
        ),
        migrations.AddField(
            model_name='petitionsource',
            name='petition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='indiaApp.petition'),
        ),
        migrations.AddField(
            model_name='petition',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petitions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='petition',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petitions_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='petitionsignature',
            name='petition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='indiaApp.petition'),
        ),
    ]
