# Generated by Django 4.2.30 on 2026-07-22 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indiaApp', '0006_petition_signature_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petition',
            options={'permissions': [('publish_petition', 'Can publish, pause, reopen and close petitions'), ('view_petition_analytics', 'Can view petition analytics')]},
        ),
        migrations.AlterModelOptions(
            name='petitionsignature',
            options={'permissions': [('moderate_petition_signatures', 'Can moderate petition signatures'), ('manually_verify_signature', 'Can manually verify a petition signature')]},
        ),
    ]
