# Generated by Django 4.2.30 on 2026-07-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiaApp', '0007_alter_petition_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='location_consented',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='moderation_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'Pending Review'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived')], db_index=True, default='review', max_length=12),
        ),
        migrations.AddField(
            model_name='story',
            name='privacy_review_complete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='public_consent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='removed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='story_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='storyreaction',
            name='reaction',
            field=models.CharField(choices=[('with_you', 'I am with you'), ('not_alone', 'You are not alone'), ('listening', 'I am listening'), ('valid', 'Your feelings are valid'), ('strength', 'Sending strength'), ('attention', 'This needs attention')], max_length=16),
        ),
    ]
