# Generated by Django 4.2.30 on 2026-07-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiaApp', '0009_preserve_approved_story_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='petitionsignature',
            name='duplicate_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='petitionsignature',
            name='is_removed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='petitionsignature',
            name='resend_available_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petitionsignature',
            name='verification_email_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='petitionsignature',
            name='verification_email_failures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='petitionsignature',
            name='verification_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
