# Generated by Django 4.2.30 on 2026-07-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiaApp', '0010_petitionsignature_duplicate_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petitionsignature',
            name='google_subject',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='petitionsignature',
            name='google_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petitionsignature',
            name='turnstile_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petitionsignature',
            name='verification_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='petitionsignature',
            name='verification_method',
            field=models.CharField(choices=[('email_legacy', 'Legacy Email'), ('google', 'Google')], db_index=True, default='email_legacy', max_length=20),
        ),
        migrations.AddField(
            model_name='petitionsignature',
            name='verified_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddConstraint(
            model_name='petitionsignature',
            constraint=models.UniqueConstraint(condition=models.Q(('google_subject', ''), _negated=True), fields=('petition', 'google_subject'), name='unique_google_subject_per_petition'),
        ),
    ]
