# Generated by Django 4.2.30 on 2026-07-23 06:13

from django.db import migrations, models
import django.db.models.deletion
import secrets

def preserve_existing_moderation_and_add_codes(apps, schema_editor):
    ListeningRequest = apps.get_model('indiaApp', 'ListeningRequest')
    StoryComment = apps.get_model('indiaApp', 'StoryComment')
    alphabet = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'
    for item in ListeningRequest.objects.filter(tracking_code__isnull=True).iterator():
        while True:
            code = 'UNM-' + ''.join(secrets.choice(alphabet) for _ in range(6))
            if not ListeningRequest.objects.filter(tracking_code=code).exists():
                item.tracking_code = code
                item.save(update_fields=['tracking_code'])
                break
    StoryComment.objects.filter(approved=True).update(status='approved')


class Migration(migrations.Migration):

    dependencies = [
        ('indiaApp', '0012_listeningrequest_publication_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningrequest',
            name='category',
            field=models.CharField(blank=True, choices=[('unsaid', 'Something I cannot tell anyone'), ('exam', 'Exam pressure'), ('family', 'Family pressure'), ('college', 'College or coaching pressure'), ('confession', 'Personal confession'), ('protest', 'Protest or accountability experience'), ('message', 'A message for other students'), ('hope', 'Hope or recovery'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='listeningrequest',
            name='comment_preference',
            field=models.CharField(choices=[('support', 'Supportive comments allowed'), ('advice', 'Advice welcome'), ('none', 'No comments')], default='support', max_length=10),
        ),
        migrations.AddField(
            model_name='listeningrequest',
            name='moderation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listeningrequest',
            name='privacy_review_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listeningrequest',
            name='public_consent_withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listeningrequest',
            name='title',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='listeningrequest',
            name='tracking_code',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='storycomment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storycomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='indiaApp.storycomment'),
        ),
        migrations.AddField(
            model_name='storycomment',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storycomment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('spam', 'Spam'), ('removed', 'Removed')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='storycomment',
            name='thread_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(preserve_existing_moderation_and_add_codes, migrations.RunPython.noop),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('harassment', 'Harassment'), ('privacy', 'Reveals identity/private details'), ('unsafe', 'Unsafe advice'), ('spam', 'Spam'), ('hate', 'Hate or abuse'), ('other', 'Other')], max_length=12)),
                ('details', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed')], db_index=True, default='pending', max_length=12)),
                ('session_key_hash', models.CharField(max_length=64)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='indiaApp.storycomment')),
            ],
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key_hash', models.CharField(max_length=64)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='indiaApp.storycomment')),
            ],
        ),
        migrations.AddConstraint(
            model_name='commentreport',
            constraint=models.UniqueConstraint(fields=('comment', 'session_key_hash'), name='unique_comment_report'),
        ),
        migrations.AddConstraint(
            model_name='commentreaction',
            constraint=models.UniqueConstraint(fields=('comment', 'session_key_hash'), name='unique_comment_reaction'),
        ),
    ]
