# Generated by Django 4.2.30 on 2026-07-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiaApp', '0013_listeningrequest_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningrequest',
            name='publication_status',
            field=models.CharField(choices=[('private', 'Private — not submitted for publication'), ('review', 'Public sharing review requested'), ('published', 'Approved and published'), ('rejected', 'Public sharing declined'), ('removed', 'Unpublished by staff')], db_index=True, default='private', max_length=12),
        ),
    ]
