# Generated by Django 4.2.30 on 2026-07-23 09:02

from django.db import migrations, models
from django.utils import timezone


def mark_sourced_stories(apps, schema_editor):
    ListeningRequest = apps.get_model('indiaApp', 'ListeningRequest')
    Story = apps.get_model('indiaApp', 'Story')
    linked_ids = ListeningRequest.objects.exclude(published_story_id=None).values_list('published_story_id', flat=True)
    Story.objects.filter(pk__in=linked_ids).update(source_was_listening_request=True)
    # Published media created from ListeningRequest always retained its private/
    # storage key. If its source was deleted before this consistency migration,
    # archive that legacy orphan rather than mistaking it for an independent Story.
    Story.objects.filter(
        source_listening_request__isnull=True,
        public_media__startswith='private/',
        story_format__in=('voice','video'),
        is_demo=False,
    ).update(
        source_was_listening_request=True,
        approved=False,
        moderation_status='archived',
        removed_at=timezone.now(),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('indiaApp', '0014_alter_listeningrequest_publication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='source_was_listening_request',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
        migrations.RunPython(mark_sourced_stories, migrations.RunPython.noop),
    ]
