# Generated by Django 4.2.30 on 2026-07-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiaApp', '0015_story_source_was_listening_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyreaction',
            name='anonymous_key',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='storyreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('anonymous_key', ''), _negated=True), fields=('story', 'anonymous_key', 'reaction'), name='unique_anonymous_story_reaction'),
        ),
    ]
