# Generated by Django 4.2.30 on 2026-07-23 16:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import indiaApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('indiaApp', '0016_storyreaction_anonymous_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('google_sub_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('legacy_email_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('identity_status', models.CharField(choices=[('confirmed_google', 'Confirmed Google'), ('provisional_legacy', 'Provisional legacy'), ('guest_only', 'Guest only'), ('merged', 'Merged'), ('inactive', 'Inactive')], db_index=True, max_length=24)),
                ('source', models.CharField(choices=[('petition_migration', 'Migrated petition verification'), ('google_sync', 'Google private sync'), ('guest_upgrade', 'Guest upgraded to Google')], max_length=24)),
                ('sync_consent_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='listeningrequest',
            name='guest_key',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='listeningrequest',
            name='kind',
            field=models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('image', 'Image'), ('video', 'Video')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='listeningrequest',
            name='media',
            field=models.FileField(blank=True, upload_to=indiaApp.models.private_upload, validators=[django.core.validators.FileExtensionValidator(['mp3', 'm4a', 'wav', 'ogg', 'webm', 'mp4', 'mov', 'jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='privateidentity',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merged_identities', to='indiaApp.privateidentity'),
        ),
        migrations.AddField(
            model_name='commentreaction',
            name='private_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_reactions', to='indiaApp.privateidentity'),
        ),
        migrations.AddField(
            model_name='listeningrequest',
            name='private_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='indiaApp.privateidentity'),
        ),
        migrations.AddField(
            model_name='petitionsignature',
            name='private_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='petition_signatures', to='indiaApp.privateidentity'),
        ),
        migrations.AddField(
            model_name='storyreaction',
            name='private_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='story_reactions', to='indiaApp.privateidentity'),
        ),
        migrations.AddConstraint(
            model_name='commentreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('private_identity__isnull', False)), fields=('comment', 'private_identity'), name='unique_private_comment_reaction'),
        ),
        migrations.AddConstraint(
            model_name='storyreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('private_identity__isnull', False)), fields=('story', 'private_identity', 'reaction'), name='unique_private_story_reaction'),
        ),
    ]
